name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: admin_login
          POSTGRES_PASSWORD: Aatif@123
          POSTGRES_DB: your_database_name
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin_login"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run database migrations
        run: |
          sudo apt-get install postgresql-client
          psql -h localhost -U admin_login -d your_database_name -c "your SQL commands here"
